apiVersion: v1
kind: Service
metadata:
  name: kuber-service
spec:
  type: NodePort
  selector:
    app: http-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 31000  # Optional: Kubernetes will auto-assign a port if you don't specify one
